# Generated by Django 4.2.29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('user_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Resource'), ('read', 'View/Read Resource'), ('update', 'Update Resource'), ('delete', 'Delete Resource'), ('export', 'Export Data'), ('import', 'Import Data'), ('permission_change', 'Permission Change'), ('security_event', 'Security Event'), ('system_error', 'System Error'), ('api_call', 'API Call'), ('configuration_change', 'Configuration Change')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('warning', 'Warning')], db_index=True, default='success', max_length=20)),
                ('resource_type', models.CharField(blank=True, choices=[('user', 'User'), ('crop', 'Crop'), ('market', 'Market'), ('notification', 'Notification'), ('schedule', 'Schedule'), ('inventory', 'Inventory'), ('ml_model', 'ML Model'), ('system', 'System')], db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_retained', models.BooleanField(default=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('visible_to_roles', models.JSONField(blank=True, default=list, help_text='List of account types that can see this log entry. Empty means visible to all.')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='activity_log.activitylog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_types', models.JSONField(default=list, help_text='List of event types this policy applies to')),
                ('severity_levels', models.JSONField(default=list, help_text='List of severity levels this policy applies to')),
                ('retention_days', models.IntegerField(default=90, help_text='Number of days to retain logs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
            },
        ),
        migrations.CreateModel(
            name='LogAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Log Aggregation',
                'verbose_name_plural': 'Log Aggregations',
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='activity_lo_timesta_e1e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_9e7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['event_type', '-timestamp'], name='activity_lo_event_t_d9f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', '-timestamp'], name='activity_lo_severity_5c8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='activity_lo_resourc_d9c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user_ip', '-timestamp'], name='activity_lo_user_ip_d5f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='logaggregation',
            index=models.Index(fields=['-date'], name='log_aggreg_date_4e7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='logaggregation',
            index=models.Index(fields=['event_type', '-date'], name='log_aggreg_event_t_3d5c4_idx'),
        ),
    ]
