# Generated by Django 6.0.3 on 2026-03-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
