# Generated by Django 6.0.3 on 2026-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buyeroffer',
            index=models.Index(fields=['-date_offered'], name='market_buye_date_of_bb8159_idx'),
        ),
        migrations.AddIndex(
            model_name='buyeroffer',
            index=models.Index(fields=['status'], name='market_buye_status_f45f0f_idx'),
        ),
    ]
