# Generated by Django 6.0.3 on 2026-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_buyeroffer_market_buye_date_of_bb8159_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledistribution',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
