# Generated by Django 6.0.3 on 2026-03-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
        ('market', '0003_scheduledistribution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('seed', 'Seeds'), ('fert', 'Fertilizer'), ('tool', 'Tools')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='buyeroffer',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
        migrations.AddField(
            model_name='buyeroffer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyeroffer',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyeroffer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='buyeroffer',
            index=models.Index(fields=['crop'], name='market_buye_crop_id_16de02_idx'),
        ),
        migrations.AddIndex(
            model_name='buyeroffer',
            index=models.Index(fields=['farmer'], name='market_buye_farmer__667623_idx'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
        migrations.AddField(
            model_name='selleroffer',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
        migrations.AddField(
            model_name='selleroffer',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='selleroffer',
            index=models.Index(fields=['-date_posted'], name='market_sell_date_po_c5d0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='selleroffer',
            index=models.Index(fields=['status'], name='market_sell_status_307666_idx'),
        ),
        migrations.AddIndex(
            model_name='selleroffer',
            index=models.Index(fields=['crop'], name='market_sell_crop_id_f9da8a_idx'),
        ),
    ]
