# Generated by Django 6.0.3 on 2026-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_inventory_salerecord_selleroffer_buyeroffer_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketprice',
            old_name='price',
            new_name='current_price',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='unit',
            field=models.CharField(default='per kg', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['crop_name'], name='market_mark_crop_na_79d204_idx'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['-last_updated'], name='market_mark_last_up_2cc122_idx'),
        ),
    ]
