# Generated by Django 4.2.29 on 2026-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_price_marketprice_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledistribution',
            name='quantity',
            field=models.CharField(blank=True, help_text='e.g., 100 sacks, 500 kg', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledistribution',
            name='recipient',
            field=models.CharField(blank=True, help_text='Name of the recipient', max_length=255, null=True),
        ),
    ]
