# Generated by Django 4.2.29 on 2026-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='humidity_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humidity percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='location',
            field=models.CharField(blank=True, help_text='Region/Province where crop is grown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='rainfall_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rainfall in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.CharField(blank=True, choices=[('Wet', 'Wet Season'), ('Dry', 'Dry Season')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_ph',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil pH level (4.0-8.5)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average temperature in Celsius', max_digits=5, null=True),
        ),
    ]
