# Generated by Django 4.2.29 on 2026-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_humidity_percent_crop_location_crop_rainfall_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
