# Generated by Django 4.2.29 on 2026-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_alter_crop_available_until_alter_crop_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
