# Generated by Django 6.0.3 on 2026-03-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_timesta_28bc36_idx',
            old_name='activity_lo_timesta_e1e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_user_id_08a8e8_idx',
            old_name='activity_lo_user_id_9e7e2_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_event_t_b9e56f_idx',
            old_name='activity_lo_event_t_d9f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_severit_8e4f95_idx',
            old_name='activity_lo_severity_5c8e0_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_resourc_080454_idx',
            old_name='activity_lo_resourc_d9c3a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_user_ip_dc0e7c_idx',
            old_name='activity_lo_user_ip_d5f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='logaggregation',
            new_name='activity_lo_date_bb6f7a_idx',
            old_name='log_aggreg_date_4e7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='logaggregation',
            new_name='activity_lo_event_t_28e94d_idx',
            old_name='log_aggreg_event_t_3d5c4_idx',
        ),
    ]
